#ifndef CONFIG_H
#define CONFIG_H
// pins 
#define BUTTON A0
#define IND_0 2
#define IND_1 3
#define MAGNET A2
#define LAMP_0 A1 // sve4a
#define LAMP_1 4 // molnia
#define BUTTON_LIGHT 13
#define DIR 6
#define STEP 7
#define ENABLE 8
#define DATA A3
#define RCK A4
#define SRCK A5
#define CHARGE_LEG 12

#define STEPS_PER_ROTATE 8
#define TIME_BEFORE_SLEEP 30000
#define TIME_BEFORE_NORMALIZE 600000
#define TIME_BEFORE_WAIT 2000
#define ELECTRIC_ENGINE_TICK 500
#define CHARGE_PER_STEP 0.5
#define UNCHARGE_PER_STEP 2.5
#define UNCHARGE_PER_STEP_WITH_ICE 1.5
#define UNCHARGE_PER_STEP_BOOST 1.5
#define CHARGE_LIGHT_TICK 500
#define STEPPER_TICK 20
#define RESULT_DISPLAY_TIME 5000
#define ELECTRIC_ENABLE_TIME 1500
#define BOOSTER_TIME_WITHOUT_UNCHARGE 3750
#define CHARGE_MAX 120.0
#define STEPPER_SPEED 1200
#define STEPPER_ACCELERATION 200
#define STEPPER_SPEED_BOOSTED 2000
#define STEPPER_ACCELERATION_BOOSTED 200
#define STEPPER_START_CHARGE 80
#define STEPPER_STOP_CHARGE 30
#define STEPPER_STOP_ACCELERATION 200
#define STEPPER_BOOST_STOP_CHARGE 80
#define STEPPER_BOOST_CHARGE 100
#define BUTTON_LIGHT_CHARGE 80
#define ENCODER_TRESHOLD 1000000
#endif
